global:
  scrape_interval: "5s"
  evaluation_interval: "5s"

scrape_configs:
  - job_name: "node"
    static_configs:
      - targets:
          - "node_exporter:9100"
  - job_name: "app"
    static_configs:
      - targets:
          - "dummy_app:8000"
