version: "3.6"
services:
  prometheus:
    build: "./containers/prometheus"
    container_name: "prometheus"
    ports:
      - "9090:9090"
  grafana:
    build: "./containers/grafana"
    container_name: "grafana"
    ports:
      - "3000:3000"
  node_exporter:
    image: "quay.io/prometheus/node-exporter"
    container_name: "node_exporter"
    ports:
      - "9100:9100"
  push_gateway:
    image: "prom/pushgateway"
    container_name: "push_gateway"
    ports:
      - "9091:9091"
  app_one:
    build: "./containers/app"
    container_name: "app_one"
    ports:
      - "8000:8000"
