{
 "title": "Prometheus Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "App One Status",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{instance=\"app_one:8000\",job=\"app_one\"}"
    }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "graph",
   "gridPos": { "h": 18, "w": 20, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "scrape_duration_seconds{instance=\"app_one:8000\",job=\"app_one\"}"
    },
    {
     "expr": "scrape_duration_seconds{instance=\"node_exporter:9100\",job=\"node\"}"
    },
    {
     "expr": "scrape_duration_seconds{instance=\"push_gateway:9091\",job=\"push_gateway\"}"
    }
   ]
  },
  {
   "title": "Push Gateway Status",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{instance=\"push_gateway:9091\",job=\"push_gateway\"}"
    }
   ]
  },
  {
   "title": "Node Exporter Status",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{instance=\"node_exporter:9100\",job=\"node\"}"
    }
   ]
  },
  {
   "title": "Python Flask App Capacity",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "demo_gauge{instance=\"app_one:8000\",job=\"app_one\"} * 100"
    }
   ]
  },
  {
   "title": "Push Gateway Example",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "time() - db_backup_last_completion_timestamp_seconds"
    }
   ]
  }
 ]
}